service:
  name: cloudkeeper-metrics-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-scripts

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  memorySize: 1024
  region: eu-central-1
  tracing: true
  environment:
    stage: ${self:custom.stage}
  iamRoleStatements:
    ${file(roleStatements.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  dbName: ${ssm:${self:custom.stage}-metrics-db-name}
  dbHost: ${ssm:${self:custom.stage}-metrics-db-host}
  dbUser: ${ssm:${self:custom.stage}-metrics-db-user}
  dbPassword: ${ssm:${self:custom.stage}-metrics-db-password}

  scripts:
    hooks:
      'before:deploy:deploy': aws s3 cp ./cloudformation.yml s3://cdn.cloudkeeper.io/cloudformation.yml

functions:
  trigger-update-lambdas:
    handler: src/update/lambda-configuration/trigger-lambda-config-update.handler
    events:
      - schedule: cron(1 * ? * * *)

  update-tenant-lambdas:
    timeout: 120
    handler: src/update/lambda-configuration/update-lambda-configurations-for-tenant.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  trigger-costs-data-update:
    handler: src/update/costs/trigger-costs-update.handler
    events:
      - schedule: cron(5 0 ? * * *)

  update-costs-for-tenant:
    timeout: 240
    handler: src/update/costs/update-costs-for-tenant.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
      finishedTopic: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-costs"

  prepare-costs-data-for-tenant:
    timeout: 240
    handler: src/update/prepare-data/prepare-costs-data-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-costs"

  trigger-dynamo-tables-update:
    handler: src/update/dynamodb-tables/trigger-dynamo-tables-update.handler
    events:
      - schedule: cron(1 * ? * * *)

  update-tenant-dynamo-tables:
    timeout: 120
    handler: src/update/dynamodb-tables/update-tenant-dynamo-tables.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
      finishedTopic: !Ref FinishedUpdatingDynamoStats

  setup-tenant:
    handler: src/setup/setup-tenant.handler

  create-tenant:
    handler: src/tenant/create-tenant.handler

  delete-tenant:
    handler: src/tenant/delete-tenant.handler

  list-tenants:
    handler: src/tenant/list-tenants.handler

  list-lambdas:
    handler: src/lambda/list-lambdas.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  list-most-expensive-lambdas:
    handler: src/lambda/list-most-expensive-lambdas.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  get-lambda:
    handler: src/lambda/get-lambda.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  get-lambda-stats:
    handler: src/lambda/get-lambda-stats.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  list-dynamo-tables:
    handler: src/dynamodb/list-tables.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  list-most-expensive-tables:
    handler: src/dynamodb/list-most-expensive-tables.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  get-dynamo-table:
    handler: src/dynamodb/get-table.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  get-dynamo-table-stats:
    handler: src/dynamodb/get-table-stats.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}

  update-tenant-lambda-stats:
    timeout: 300
    handler: src/update/lambda-stats/update-tenant-lambda-stats.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
      finishedTopic: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-lambda-stats"

  prepare-lambda-data-for-tenant:
    timeout: 240
    handler: src/update/prepare-data/prepare-lambda-data-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-lambda-stats"

  update-tenant-dynamo-stats:
    timeout: 300
    handler: src/update/dynamodb-table-stats/update-tenant-dynamo-stats.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
      finishedTopic: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-dynamo-stats"

  prepare-dynamo-data-for-tenant:
    timeout: 240
    handler: src/update/prepare-data/prepare-dynamo-data-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-dynamo-stats"

  update-dynamo-events-for-tenant:
    timeout: 300
    handler: src/update/events/update-dynamo-events-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-dynamo-stats"

  update-lambda-events-for-tenant:
    timeout: 300
    handler: src/update/events/update-lambda-events-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-lambda-stats"

  update-costs-events-for-tenant:
    timeout: 120
    handler: src/update/events/update-costs-events-for-tenant.handler
    environment:
      bucket: ${self:custom.stage}-cloudkeeper-tenant-data
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
      azureClientId: ${ssm:azure-client-id}
      azureClientSecret: ${ssm:azure-client-secret}
      azureSubscriptionId: ${ssm:azure-cognitive-subscription-id}
      azureDomain: ${ssm:azure-domain}
    events:
      - sns:
          arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.stage}-finished-updating-costs"

  update-pricing:
    handler: src/update/pricing/update-pricing.handler
    environment:
      dbName: ${self:custom.dbName}
      dbHost: ${self:custom.dbHost}
      dbUser: ${self:custom.dbUser}
      dbPassword: ${self:custom.dbPassword}
    events:
      - schedule: cron(1 0 ? * * *)

resources:
  Resources:
    Tenants:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stage}-cloudkeeper-tenants
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TenantAccess:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stage}-cloudkeeper-tenant-users
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: tenantId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: tenantId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenantIdIndex
            KeySchema:
              - AttributeName: tenantId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    FinishedUpdatingLambdaStats:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: ${self:custom.stage}-finished-updating-lambda-stats
        TopicName: ${self:custom.stage}-finished-updating-lambda-stats

    FinishedUpdatingDynamoStats:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: ${self:custom.stage}-finished-updating-dynamo-stats
        TopicName: ${self:custom.stage}-finished-updating-dynamo-stats

    FinishedUpdatingCosts:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: ${self:custom.stage}-finished-updating-costs
        TopicName: ${self:custom.stage}-finished-updating-costs

    CloudkeeperTenantData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-cloudkeeper-tenant-data
